version: "3.9"

services:
  web:
    build: .
    container_name: search_app_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://ihringen_appuser:ihringen@db:5432/ihringen
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: search_app_db
    environment:
      POSTGRES_DB: ihringen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./data:/data
    restart: unless-stopped

volumes:
  pgdata:
